"""Emit docker-compose.yml for the real-NAT topology.

Topology (three separate Docker networks = three separate address realms):

    lanA 10.10.1.0/24            pubnet 172.30.0.0/24            lanB 10.10.2.0/24
    (internal)                   ("the internet")               (internal)
    +---------+   +--------+     +-------------+     +--------+   +---------+
    | nodeA   |---|  gwA   |=====| rendezvous  |=====|  gwB   |---| nodeB   |
    | .10     |   |.2 | .2 |     |   .10       |     |.3 | .2 |   | .10     |
    +---------+   +--------+     +-------------+     +--------+   +---------+
                  NAT (MASQ)                          NAT (MASQ)

nodeA and nodeB sit on DIFFERENT internal LANs and can reach NOTHING off their
LAN except through their gateway's real netfilter NAT. Neither can address the
other directly — the only way they ever exchange a datagram is if the
rendezvous-coordinated UDP hole-punch actually opens both NATs. That is the
claim loopback tests cannot make.

Run:  python gen_compose.py > docker-compose.yml
Env:  NAT_SYMMETRIC=1  -> gateways use per-destination port allocation, so the
                          punch is expected to FAIL (demonstrates the case that
                          needs relay fallback, phase task T4).
"""
import os

from nacl.signing import SigningKey

from swarmint.network.identity import Identity


def node_id(seed: int) -> str:
    seed_bytes = seed.to_bytes(4, "big").rjust(32, b"\0")
    return Identity(SigningKey(seed_bytes)).node_id.hex()


R, A, B = node_id(0), node_id(1), node_id(2)
SYMMETRIC = os.environ.get("NAT_SYMMETRIC", "0")
DURATION = os.environ.get("SWARM_DURATION_S", "70")

COMPOSE = f"""# GENERATED by gen_compose.py -- do not edit by hand.
# node_ids are deterministic from seeds: rendezvous=0, nodeA=1, nodeB=2.
name: swarmint-nat-test

x-image: &img
  image: swarmint-nat:test
  build:
    context: ../..
    dockerfile: docker/nat-test/Dockerfile

networks:
  pubnet:
    ipam:
      config: [{{subnet: 172.30.0.0/24}}]
  # NOT `internal: true`: an internal network makes Docker drop any off-subnet
  # L3 packet on the bridge at the HOST level, so our in-LAN gateway container
  # never even sees traffic bound for the pubnet. Plain bridges still can't
  # reach pubnet directly (Docker isolates the two bridges), so the only path
  # off-LAN remains the gateway we point the default route at -> real NAT.
  lanA:
    ipam:
      config: [{{subnet: 10.10.1.0/24}}]
  lanB:
    ipam:
      config: [{{subnet: 10.10.2.0/24}}]

services:
  rendezvous:
    <<: *img
    cap_add: [NET_ADMIN]
    networks:
      pubnet: {{ipv4_address: 172.30.0.10}}
    environment:
      SWARM_KIND: swarm
      SWARM_ROLE: rendezvous
      SWARM_SEED: "0"
      SWARM_ADVERTISE_HOST: 172.30.0.10
      SWARM_GOSSIP_PORT: "9001"
      SWARM_DHT_PORT: "9002"
      SWARM_DURATION_S: "{DURATION}"

  gwA:
    <<: *img
    cap_add: [NET_ADMIN]
    sysctls: {{net.ipv4.ip_forward: "1"}}
    networks:
      lanA: {{ipv4_address: 10.10.1.2}}
      pubnet: {{ipv4_address: 172.30.0.2}}
    environment:
      SWARM_KIND: gateway
      LAN_SUBNET: 10.10.1.0/24
      NAT_SYMMETRIC: "{SYMMETRIC}"

  gwB:
    <<: *img
    cap_add: [NET_ADMIN]
    sysctls: {{net.ipv4.ip_forward: "1"}}
    networks:
      lanB: {{ipv4_address: 10.10.2.2}}
      pubnet: {{ipv4_address: 172.30.0.3}}
    environment:
      SWARM_KIND: gateway
      LAN_SUBNET: 10.10.2.0/24
      NAT_SYMMETRIC: "{SYMMETRIC}"

  nodeA:
    <<: *img
    cap_add: [NET_ADMIN]
    depends_on: [rendezvous, gwA]
    networks:
      lanA: {{ipv4_address: 10.10.1.10}}
    environment:
      SWARM_KIND: swarm
      SWARM_ROLE: node
      SWARM_SEED: "1"
      SWARM_ADVERTISE_HOST: 10.10.1.10
      SWARM_GATEWAY: 10.10.1.2
      SWARM_GOSSIP_PORT: "9001"
      SWARM_DHT_PORT: "9002"
      SWARM_RENDEZVOUS_HOST: 172.30.0.10
      SWARM_RENDEZVOUS_DHT_PORT: "9002"
      SWARM_RENDEZVOUS_ID: "{R}"
      SWARM_PUNCH_PEERS: "{B}"
      SWARM_DURATION_S: "{DURATION}"

  nodeB:
    <<: *img
    cap_add: [NET_ADMIN]
    depends_on: [rendezvous, gwB]
    networks:
      lanB: {{ipv4_address: 10.10.2.10}}
    environment:
      SWARM_KIND: swarm
      SWARM_ROLE: node
      SWARM_SEED: "2"
      SWARM_ADVERTISE_HOST: 10.10.2.10
      SWARM_GATEWAY: 10.10.2.2
      SWARM_GOSSIP_PORT: "9001"
      SWARM_DHT_PORT: "9002"
      SWARM_RENDEZVOUS_HOST: 172.30.0.10
      SWARM_RENDEZVOUS_DHT_PORT: "9002"
      SWARM_RENDEZVOUS_ID: "{R}"
      SWARM_PUNCH_PEERS: "{A}"
      SWARM_DURATION_S: "{DURATION}"
"""

if __name__ == "__main__":
    print(COMPOSE, end="")
