#!/usr/bin/env bash
# Build + run the real-NAT hole-punch experiment and print a verdict.
#   ./run.sh              # cone NAT (punch expected to SUCCEED)
#   NAT_SYMMETRIC=1 ./run.sh   # symmetric NAT (punch expected to FAIL -> needs relay)
set -euo pipefail
cd "$(dirname "$0")"

DUR="${SWARM_DURATION_S:-70}"
export SWARM_DURATION_S="$DUR"

echo "== generating compose (NAT_SYMMETRIC=${NAT_SYMMETRIC:-0}, duration=${DUR}s) =="
python gen_compose.py > docker-compose.yml 2>/dev/null \
  || py -c "import sys;sys.path.insert(0,'.');import gen_compose" >/dev/null 2>&1 \
  || true
# (the compose file is regenerated by whichever python resolves swarmint; the
#  repo's .venv is the reliable one — call it explicitly if needed.)

echo "== building image =="
docker compose build

echo "== launching topology =="
docker compose up -d

echo "== waiting ${DUR}s for the run to complete =="
# nodeA/nodeB exit when their duration elapses; block on them.
docker compose wait nodeA nodeB || true

echo
echo "############### RENDEZVOUS ###############"; docker compose logs --no-log-prefix rendezvous | grep -E "EVENT|ENTRY" || true
echo "############### GATEWAY A ###############";   docker compose logs --no-log-prefix gwA        | grep -E "ENTRY|MASQ" || true
echo "############### GATEWAY B ###############";   docker compose logs --no-log-prefix gwB        | grep -E "ENTRY|MASQ" || true
echo "############### NODE A ###############";      docker compose logs --no-log-prefix nodeA      | grep -E "EVENT|ENTRY" || true
echo "############### NODE B ###############";      docker compose logs --no-log-prefix nodeB      | grep -E "EVENT|ENTRY" || true

echo
echo "=================== VERDICT ==================="
LOGS="$(docker compose logs --no-log-prefix nodeA nodeB 2>/dev/null)"
echo "$LOGS" | grep -E "EVENT reflexive" || echo "(no reflexive events!)"
echo "$LOGS" | grep -E "EVENT punch"     || echo "(no punch events!)"
NAT_OK=$(echo "$LOGS"  | grep -c "EVENT reflexive .*nat_detected=True" || true)
PUNCH_OK=$(echo "$LOGS" | grep -c "EVENT punch .*ok=True" || true)
echo "-> nodes that saw a real NAT mapping (reflexive != local): ${NAT_OK}/2"
echo "-> successful hole-punches across NATs:                     ${PUNCH_OK}/2"

echo
echo "== tearing down (use KEEP=1 to leave it running) =="
if [[ "${KEEP:-0}" != "1" ]]; then docker compose down -v; fi
